const $=s=>document.querySelector(s),gate=$('#gate'),enter=$('#enter'),audio=$('#audio'),music=$('#music'),glow=$('#glow');document.body.classList.add('lock');audio.volume=.38;
function setState(on){music.classList.toggle('paused',!on);music.querySelector('em').textContent=on?'BGM ON':'BGM OFF'}
function go(){if(gate.classList.contains('hide'))return;gate.classList.add('hide');document.body.classList.remove('lock');audio.play().then(()=>setState(true)).catch(()=>setState(false));startTerminal()}
enter.onclick=go;addEventListener('keydown',e=>{if(!gate.classList.contains('hide')&&(e.key==='Enter'||e.code==='Space')){e.preventDefault();go()}});music.onclick=()=>audio.paused?audio.play().then(()=>setState(true)):(audio.pause(),setState(false));
let emberTick=0;addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';if(++emberTick%3===0){let x=document.createElement('i');x.className='ember';x.style.left=e.clientX+'px';x.style.top=e.clientY+'px';x.style.setProperty('--dx',(Math.random()*30-15)+'px');x.style.setProperty('--dy',(Math.random()*35+10)+'px');document.body.append(x);setTimeout(()=>x.remove(),750)}});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=e=>{let el=$(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}});
const match=$('#matchModal'),apply=$('#applyModal');function show(m){m.classList.add('show')}function hide(m){m.classList.remove('show')}$('#matchLaunch').onclick=()=>show(match);$('#modalX').onclick=()=>hide(match);$('#applyBtn').onclick=()=>show(apply);$('#partnerSlot').onclick=()=>show(apply);$('#applyX').onclick=()=>hide(apply);[match,apply].forEach(m=>m.onclick=e=>{if(e.target===m)hide(m)});
$('#calcMatch').onclick=()=>{let vals=['#qMap','#qDiscord','#qTalk','#qOnline'].map(x=>+$(x).value),score=vals.reduce((a,b)=>a+b,0);let out=$('#matchResult'),n=0,target=Math.min(100,score);out.querySelector('p').textContent=target>=85?'🔥 거의 같은 파티 체질. 오픈채팅 루트 추천!':target>=65?'❤️ 꽤 잘 맞을 가능성 있음. 대화부터 해봐요.':target>=40?'⚡ 일단 대화해보면 답 나올 듯!':'💀 플레이 스타일 차이가 조금 큰 편!';let t=setInterval(()=>{n=Math.min(target,n+2);out.querySelector('strong').textContent=n+'%';if(n>=target)clearInterval(t)},18)};
const run=$('#runaway');run.onmouseenter=()=>{let card=run.closest('.modalCard').getBoundingClientRect(),r=run.getBoundingClientRect();run.style.position='absolute';run.style.width=Math.min(190,r.width)+'px';run.style.left=Math.max(0,Math.random()*(card.width-220))+'px';run.style.top=(70+Math.random()*90)+'px'};
let typed=false;function startTerminal(){if(typed)return;typed=true;let text='> ASA PROFILE LOADING...\n> PLAYER : 빨간색 인페르노\n> AGE : 24 / MALE\n> MAIN : CHLOE\n> MAP : EVENT / HARDCORE\n> DISCORD : REQUIRED\n> STATUS : ONLINE // WAITING FOR DUO\n> PARTNER SLOT : EMPTY ♥';let i=0,t=$('#terminalText');let timer=setInterval(()=>{t.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(timer)},28)}
let secretKey='';addEventListener('keydown',e=>{if(e.key.length===1){secretKey=(secretKey+e.key.toUpperCase()).slice(-5);if(secretKey==='CHLOE'){let s=$('#secret');s.classList.add('on');setTimeout(()=>s.classList.remove('on'),1800);secretKey=''}}});
const canvas=$('#visualizer'),ctx=canvas.getContext('2d');let ac,analyser,src,data;function initViz(){if(ac)return;try{ac=new (window.AudioContext||window.webkitAudioContext)();analyser=ac.createAnalyser();analyser.fftSize=128;src=ac.createMediaElementSource(audio);src.connect(analyser);analyser.connect(ac.destination);data=new Uint8Array(analyser.frequencyBinCount)}catch(e){}}audio.addEventListener('play',()=>{initViz();if(ac?.state==='suspended')ac.resume()});function draw(){requestAnimationFrame(draw);let dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);if(!analyser)return;analyser.getByteFrequencyData(data);let bw=w/data.length;ctx.fillStyle='#ff2525';data.forEach((v,i)=>{let bh=v/255*h;ctx.fillRect(i*bw,h-bh,Math.max(1,bw-2),bh)})}draw();
