const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],gate=$('#gate'),enter=$('#enter'),audio=$('#audio'),music=$('#music'),mute=$('#mute'),volume=$('#volume'),volumeValue=$('#volumeValue'),glow=$('#glow');document.body.classList.add('lock');const savedVolume=Math.max(0,Math.min(1,Number(localStorage.getItem('infernoVolume')??.22)));audio.volume=savedVolume;volume.value=Math.round(savedVolume*100);volumeValue.textContent=volume.value+'%';
function setState(on){music.classList.toggle('paused',!on);music.querySelector('em').textContent=on?'BGM ON':'BGM OFF'}
function go(){if(gate.classList.contains('hide'))return;gate.classList.add('hide');document.body.classList.remove('lock');audio.play().then(()=>setState(true)).catch(()=>setState(false));startTerminal();toast('WELCOME // INFERNO')}
enter.onclick=go;addEventListener('keydown',e=>{if(!gate.classList.contains('hide')&&(e.key==='Enter'||e.code==='Space')){e.preventDefault();go()}});music.onclick=()=>audio.paused?audio.play().then(()=>setState(true)):(audio.pause(),setState(false));
function syncVolume(){const v=Math.max(0,Math.min(100,+volume.value));audio.volume=v/100;audio.muted=false;volumeValue.textContent=v+'%';mute.textContent=v===0?'🔇':v<45?'🔉':'🔊';localStorage.setItem('infernoVolume',String(v/100))}volume.addEventListener('input',syncVolume);mute.addEventListener('click',()=>{audio.muted=!audio.muted;mute.textContent=audio.muted?'🔇':audio.volume<.45?'🔉':'🔊';volumeValue.textContent=audio.muted?'MUTE':Math.round(audio.volume*100)+'%'});
let emberTick=0;addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px';if(innerWidth>760&&++emberTick%4===0){let x=document.createElement('i');x.className='ember';x.style.left=e.clientX+'px';x.style.top=e.clientY+'px';x.style.setProperty('--dx',(Math.random()*30-15)+'px');x.style.setProperty('--dy',(Math.random()*35+10)+'px');document.body.append(x);setTimeout(()=>x.remove(),750)}});
$$('a[href^="#"]').forEach(a=>a.onclick=e=>{let el=$(a.getAttribute('href'));if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'})}});
addEventListener('scroll',()=>{$('#progress').style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%'});const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
const match=$('#matchModal'),apply=$('#applyModal');function show(m){m.classList.add('show');document.body.style.overflow='hidden'}function hide(m){m.classList.remove('show');document.body.style.overflow=''}$('#matchLaunch').onclick=()=>show(match);$('#matchLaunch2').onclick=()=>show(match);$('#modalX').onclick=()=>hide(match);$('#applyBtn').onclick=()=>show(apply);$('#partnerSlot').onclick=()=>show(apply);$('#applyX').onclick=()=>hide(apply);[match,apply].forEach(m=>m.onclick=e=>{if(e.target===m)hide(m)});addEventListener('keydown',e=>{if(e.key==='Escape'){$$('.modal.show').forEach(hide)}});
$('#calcMatch').onclick=()=>{let vals=['#qMap','#qDiscord','#qTalk','#qOnline'].map(x=>+$(x).value),score=vals.reduce((a,b)=>a+b,0),out=$('#matchResult'),n=0,target=Math.min(100,score);out.querySelector('p').textContent=target>=85?'🔥 거의 같은 파티 체질. 대화 루트 열어봐도 좋을 듯!':target>=65?'❤️ 꽤 잘 맞을 가능성 있음. 대화부터 해봐요.':target>=40?'⚡ 일단 대화해보면 답 나올 듯!':'💀 플레이 스타일 차이가 조금 큰 편!';out.querySelector('.meter i').style.width=target+'%';let t=setInterval(()=>{n=Math.min(target,n+2);out.querySelector('strong').textContent=n+'%';if(n>=target){clearInterval(t);toast('MATCH RATE // '+target+'%')}},18)};
const run=$('#runaway');function flee(){let card=run.closest('.modalCard').getBoundingClientRect(),r=run.getBoundingClientRect();run.style.position='absolute';run.style.width=Math.min(190,r.width)+'px';run.style.left=Math.max(5,Math.random()*(card.width-220))+'px';run.style.top=(100+Math.random()*120)+'px'}run.onmouseenter=flee;run.onclick=flee;
let typed=false;function startTerminal(){if(typed)return;typed=true;let text='> ASA PROFILE LOADING...\n> PLAYER : 빨간색 인페르노\n> AGE : 24 / MALE\n> MAIN : CHLOE\n> MAP : EVENT / HARDCORE\n> ACTIVITY : FULL TIME\n> DISCORD : REQUIRED\n> COUPLE RING : LEVEL-UP READY\n> STATUS : ONLINE // WAITING FOR DUO\n> PARTNER SLOT : EMPTY ♥';let i=0,t=$('#terminalText');let timer=setInterval(()=>{t.textContent=text.slice(0,++i);if(i>=text.length)clearInterval(timer)},24)}
let secretKey='';addEventListener('keydown',e=>{if(e.key.length===1&&!['SELECT','INPUT','TEXTAREA'].includes(document.activeElement.tagName)){secretKey=(secretKey+e.key.toUpperCase()).slice(-5);if(secretKey==='CHLOE'){let s=$('#secret');s.classList.add('on');toast('SECRET SIGNAL FOUND');setTimeout(()=>s.classList.remove('on'),1900);secretKey=''}}});function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('on');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('on'),1800)}
const canvas=$('#visualizer'),ctx=canvas.getContext('2d');let ac,analyser,src,data;function initViz(){if(ac)return;try{ac=new (window.AudioContext||window.webkitAudioContext)();analyser=ac.createAnalyser();analyser.fftSize=128;analyser.smoothingTimeConstant=.8;src=ac.createMediaElementSource(audio);src.connect(analyser);analyser.connect(ac.destination);data=new Uint8Array(analyser.frequencyBinCount)}catch(e){}}audio.addEventListener('play',()=>{initViz();if(ac?.state==='suspended')ac.resume()});function draw(){requestAnimationFrame(draw);let dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);if(!analyser)return;analyser.getByteFrequencyData(data);let bw=w/data.length;data.forEach((v,i)=>{let bh=v/255*h;ctx.fillStyle=`rgba(255,${30+Math.floor(v/8)},35,.85)`;ctx.fillRect(i*bw,h-bh,Math.max(1,bw-2),bh)})}draw();
